### ISSUE TITLE
Linux Midi port names

### ISSUE THREAD

**Issue by ngradwohl** [llloret/osmid#41] opened 2017-04-17 14:37 UTC
On a linux system the alsa midi port names are prefixed by the device name and conain a ":", which is not allowed by the regex in `OscInProcessor::ProcessMessage
`
it works when the regex gets changed to 

`regex addressRegex("/(([[:alnum:]]|\\:|\\s|\\*)+)/(([[:alnum:]]|_)+)");`

**Comment by llloret** [comment] 2017-04-17 19:53
Hi, thanks for reporting. I'm not sure what the problem is exactly, since things seem to work on Linux. Can you provide some more info, and I'll have a look?

Thank you again.

The project is very young still, so having people like you using it and reporting problems is really great!

**Comment by ngradwohl** [comment] 2017-04-18 02:52
on a linux system using alsa '`o2m -l`" reports the midi port names in the format "<devicename>: <portname>' 

for example on my box my launchpad mini gets reported as 
   ```
...
   (23): Launchpad Mini: Launchpad Mini MIDI 1
  ... 

```
so when I send a note on osc message using sonic pi it works if I send it to all devices with 
`/*/note_off `
But since I have a lot of midi devices connected to my box I want to send the messages to a specific port. Unfortunately this results in a osc message like 
`"/Launchpad Mini: Launchpad Mini MIDI 1/note_on" `
which results in an address unknown error because the regex rejects the `":"` 

so it can be fixed by adding `\\:`  to the `addressRegex` in OscInProcessor like shown above

**Comment by llloret** [comment] 2017-04-19 13:07
Hi, @ngradwohl, I have committed your proposed fix to `master`. Can you confirm that `master` works ok for you now?

Thanks,
Luis

**Closed as completed** 2017-04-19 13:06 UTC

**Comment by ngradwohl** [comment] 2017-04-19 13:29
Hi, yes works - thanks!
